---
  - name: Install git with yum
    yum: name=git
    when: ansible_os_family == "RedHat"

  - name: Install git with apt
    apt: name=git
    when: ansible_os_family == "Debian"

  - name: Download app with git
    git:
      repo: https://aegis_12@bitbucket.org/aegis_12/pergamo.git
      dest: "/usr/local/go//src"

  - name: Create GOBIN
    file:
      path: "/usr/local/go/bin"
      state: directory

  - name: Install aplication with GO
    command: go install main.go
      creates: "/usr/local/go/bin/main"
      chdir: "/usr/local/go/src/pergamo"
      environment:
        GOBIN: "/usr/local/go/bin"
        PATH: "{{ ansible_env.PATH }}:/usr/local/go/bin"
