---
  - name: Install git with yum
    yum: name=git
    when: ansible_os_family == "RedHat"

  - name: Install git with apt
    apt: name=git
    when: ansible_os_family == "Debian"

  - name: Download app with git
    git:
      repo: https://aegis_12@bitbucket.org/aegis_12/pergamo.git
      dest: "{{ ansible_env.GOPATH }}/src"

  - name: Create GOBIN
    file:
      path: "{{ ansible_env.GOPATH }}/bin"
      state: directory

  - name: Install aplication with GO
    command: go install main.go
      creates: "{{ ansible_env.GOPATH }}/bin/main"
      chdir: "{{ ansible_env.GOPATH }}/src/pergamo"
      environment:
        GOBIN: "{{ ansible_env.GOPATH }}/bin"
        PATH: "{{ ansible_env.PATH }}:{{ ansible_env.GOPATH }}/bin"
